### ISSUE TITLE
about get_gpus()

### ISSUE THREAD

**Issue by Lsiming** [JiahuiYu/generative_inpainting#105]
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    ng.get_gpus(1)
  File "/usr/local/lib/python3.5/dist-packages/neuralgym-0.0.1-py3.5.egg/neuralgym/utils/gpus.py", line 54, in get_gpus
ValueError: invalid literal for int() with base 10: 'gpu'

Sometimes the above problems appear in the test. Have you ever encountered them？

**Comment by JiahuiYu** [comment]
@Lsiming Please use python 3.6. Also please search over closed issues and I think there are many related question.
