### ISSUE TITLE
while running the inpaints_ops.py error

### ISSUE THREAD

**Issue by akshay951228** [JiahuiYu/generative_inpainting#119]
error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inpaint_ops.py", line 513, in <module>
    test_contextual_attention(args)
  File "inpaint_ops.py", line 360, in test_contextual_attention
    training=False, fuse=False)
  File "inpaint_ops.py", line 313, in contextual_attention
    offsets.set_shape(int_bs[:3] + [2])
  File "/anaconda3/envs/dev_py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 528, in set_shape
    raise ValueError(str(e))
**ValueError: Dimension 1 in both shapes must be equal, but are 166 and 64. Shapes are [1,166,250,2] and [1,64,64,2]..**

can you help me please where I was going wrong

**Comment by JiahuiYu** [comment]
You can leave a message under #67. I think you two have the same issue, but he probably have solved it.
