### ISSUE TITLE
ValueError: Cannot feed value of shape (32, 576, 768, 3) for Tensor 'Placeholder:0', which has shape '(?, 768, 576, 3)'

### ISSUE THREAD

**Issue by akshay951228** [JiahuiYu/generative_inpainting#121]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chandu/akshay/dev_py36/lib/python3.5/site-packages/neuralgym/data/feeding_queue_runner.py", line 197, in _run
    sess.run(enqueue_op, feed_dict)
  File "/home/chandu/akshay/dev_py36/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/chandu/akshay/dev_py36/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1076, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 576, 768, 3) for Tensor 'Placeholder:0', which has shape '(?, 768, 576, 3)'

### In inpaint.yml 
I have given
**IMG_SHAPES: [768,576, 3]**

**It work well when I have give height and width same**

I'm new to Deep learning and tensorflow
can you please throw a light where I can make the modification in code

**Comment by JiahuiYu** [comment]
Please try to change `IMG_SHAPES: [768,576, 3]` to `IMG_SHAPES: [576,768, 3]`.

**Comment by akshay951228** [comment]
no luck ValueError: Cannot feed value of shape (32, 768, 576, 3) for Tensor 'Placeholder:0', which has shape '(?, 576, 768, 3)'

I have image shape [768,576, 3] but in **inpant.yml** I define image shape [512,512,3] my doubt was will it resize itself?

**Comment by tangeroo** [comment]
@akshay951228 Did you solve this problem?

**Comment by JiahuiYu** [comment]
@akshay951228 @tangeroo I guess the shape mis-alignment is in the batch dimension. Did you modify something in this code? If not, could you try tensorflow with our tested versions?
