### ISSUE TITLE
ERROR:File "train.py", line 49, in <module>     config = ng.Config(sys.argv[1])

### ISSUE THREAD

**Issue by JinMengKang** [JiahuiYu/generative_inpainting#125]
Thank you for your excellent work!When I ran the Free-Form code.The following error occurred.Can you help me ?Thank you very much.
[2018-09-06 19:01:29 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[2018-09-06 19:01:29 @__init__.py:80] Saving logging to file: neuralgym_logs/20180906190129318090.
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    config = ng.Config(sys.argv[1])
IndexError: list index out of range

**Comment by JinMengKang** [comment]
When I run 'python train.py -1' The Following error occurred:

2018-09-06 19:46:27 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[2018-09-06 19:46:27 @__init__.py:80] Saving logging to file: neuralgym_logs/20180906194627677265.
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    config = ng.Config(sys.argv[1])
  File "/home/kjm/.local/lib/python3.5/site-packages/neuralgym/utils/config.py", line 85, in __init__
    assert os.path.exists(filename), "ERROR: Config File doesn't exist."
AssertionError: ERROR: Config File doesn't exist.

They may be the same problem.

**Comment by JinMengKang** [comment]
Sorry, after I tried, I corrected this mistake.

**Comment by itsRaymanda** [comment]
> 感谢您的出色工作！当我运行自由格式代码时。出现以下错误。您能帮帮我吗？非常感谢。 [2018-09-06 19:01:29 @ **init** .py:79] 设置根记录器。使用 neuralgym.unset_logger() 取消设置记录器。 [2018-09-06 19:01:29 @ **init** .py:80] 将日志保存到文件：neuralgym_logs/20180906190129318090。 Traceback（最近一次调用最后一次）： 文件“train.py”，第 49 行，在 config = ng.Config(sys.argv[1]) IndexError: list index out of range

Can you tell me how to solve this question,please? Because I have the same question as you.
