### ISSUE TITLE
Running error in train.py

### ISSUE THREAD

**Issue by JinMengKang** [JiahuiYu/generative_inpainting#126]
Thank you for your excellent work! I have some trouble when I ran the Free-Form codes.
And I use python3.5+tensorflow 1.4.0, I also resized celeba picture to 256*256*3.
Here are the parameters in the inpaint.yml:

STATIC_VIEW_SIZE: 30
IMG_SHAPES: [256, 256, 3]
HEIGHT: 128
WIDTH: 128
MAX_DELTA_HEIGHT: 32
MAX_DELTA_WIDTH: 32
BATCH_SIZE: 16
VERTICAL_MARGIN: 0
HORIZONTAL_MARGIN: 0
MAXVERTEX: 5
MAXANGLE: 4.0 #pi
MAXLENGTH: 40
MAXBRUSHWIDTH: 10

And here are the errors :+1: 

[2018-09-07 20:41:41 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[2018-09-07 20:41:41 @__init__.py:80] Saving logging to file: neuralgym_logs/20180907204141238258.
[2018-09-07 20:41:42 @config.py:92] ---------------------------------- APP CONFIG ----------------------------------
[2018-09-07 20:41:42 @config.py:119] GRAMS_LOSS: False
[2018-09-07 20:41:42 @config.py:119] GAN_LOSS_ALPHA: 0.001
[2018-09-07 20:41:42 @config.py:111] DATA_FLIST: 
[2018-09-07 20:41:42 @config.py:119]   celeba: ['/home/kjm/Desktop/inpainting/GatedConvolution/celeba_data/data_flist/train_shuffled.flist', '/home/kjm/Desktop/inpainting/GatedConvolution/celeba_data/data_flist/validation_shuffled.flist']
[2018-09-07 20:41:42 @config.py:119] COARSE_L1_ALPHA: 1.2
[2018-09-07 20:41:42 @config.py:119] GPU_ID: [0]
[2018-09-07 20:41:42 @config.py:119] RANDOM_SEED: False
[2018-09-07 20:41:42 @config.py:119] MAXBRUSHWIDTH: 10
[2018-09-07 20:41:42 @config.py:119] VIZ_MAX_OUT: 10
[2018-09-07 20:41:42 @config.py:119] WGAN_GP_LAMBDA: 10
[2018-09-07 20:41:42 @config.py:119] MAX_DELTA_HEIGHT: 32
[2018-09-07 20:41:42 @config.py:119] TV_LOSS: False
[2018-09-07 20:41:42 @config.py:119] MAX_DELTA_WIDTH: 32
[2018-09-07 20:41:42 @config.py:119] PADDING: SAME
[2018-09-07 20:41:42 @config.py:119] LOAD_VGG_MODEL: False
[2018-09-07 20:41:42 @config.py:119] AE_LOSS: True
[2018-09-07 20:41:42 @config.py:119] VAL: True
[2018-09-07 20:41:42 @config.py:119] TV_LOSS_ALPHA: 0.0
[2018-09-07 20:41:42 @config.py:119] MODEL_RESTORE: 201809_celeba_model
[2018-09-07 20:41:42 @config.py:119] GAN: sn_pgan
[2018-09-07 20:41:42 @config.py:119] GRADIENT_CLIP: False
[2018-09-07 20:41:42 @config.py:119] MAXVERTEX: 5
[2018-09-07 20:41:42 @config.py:119] BATCH_SIZE: 16
[2018-09-07 20:41:42 @config.py:119] DISCOUNTED_MASK: True
[2018-09-07 20:41:42 @config.py:119] GRAMS_LOSS_ALPHA: 50
[2018-09-07 20:41:42 @config.py:119] TRAIN_SPE: 10000
[2018-09-07 20:41:42 @config.py:119] GRADS_SUMMARY: False
[2018-09-07 20:41:42 @config.py:119] GLOBAL_DCGAN_LOSS_ALPHA: 1.0
[2018-09-07 20:41:42 @config.py:119] GLOBAL_WGAN_LOSS_ALPHA: 1.0
[2018-09-07 20:41:42 @config.py:119] STATIC_VIEW_SIZE: 30
[2018-09-07 20:41:42 @config.py:119] MAX_ITERS: 1000000
[2018-09-07 20:41:42 @config.py:119] DATASET: celeba
[2018-09-07 20:41:42 @config.py:119] VAL_PSTEPS: 1000
[2018-09-07 20:41:42 @config.py:119] HEIGHT: 128
[2018-09-07 20:41:42 @config.py:119] L1_LOSS_ALPHA: 1.2
[2018-09-07 20:41:42 @config.py:119] HORIZONTAL_MARGIN: 0
[2018-09-07 20:41:42 @config.py:119] VERTICAL_MARGIN: 0
[2018-09-07 20:41:42 @config.py:119] GAN_WITH_GUIDE: False
[2018-09-07 20:41:42 @config.py:119] GAN_WITH_MASK: True
[2018-09-07 20:41:42 @config.py:119] GRADIENT_CLIP_VALUE: 0.1
[2018-09-07 20:41:42 @config.py:119] MASKDATASET: irrmask
[2018-09-07 20:41:42 @config.py:119] PRETRAIN_COARSE_NETWORK: False
[2018-09-07 20:41:42 @config.py:119] MAXANGLE: 4.0
[2018-09-07 20:41:42 @config.py:119] RANDOM_CROP: False
[2018-09-07 20:41:42 @config.py:119] WIDTH: 128
[2018-09-07 20:41:42 @config.py:119] LOG_DIR: full_model_celeba_256
[2018-09-07 20:41:42 @config.py:119] NUM_GPUS: 1
[2018-09-07 20:41:42 @config.py:119] MASKFROMFILE: False
[2018-09-07 20:41:42 @config.py:119] L1_LOSS: True
[2018-09-07 20:41:42 @config.py:119] IMG_SHAPES: [256, 256, 3]
[2018-09-07 20:41:42 @config.py:119] AE_LOSS_ALPHA: 1.2
[2018-09-07 20:41:42 @config.py:119] VGG_MODEL_FILE: data/model_zoo/vgg16.npz
[2018-09-07 20:41:42 @config.py:119] MAXLENGTH: 40
[2018-09-07 20:41:42 @config.py:119] SPATIAL_DISCOUNTING_GAMMA: 0.9
[2018-09-07 20:41:42 @config.py:119] FEATURE_LOSS_ALPHA: 0.01
[2018-09-07 20:41:42 @config.py:119] FEATURE_LOSS: False
[2018-09-07 20:41:42 @config.py:94] --------------------------------------------------------------------------------
[2018-09-07 20:41:42 @gpus.py:20] Set env: CUDA_VISIBLE_DEVICES=[0].
[2018-09-07 20:41:42 @dataset.py:26] --------------------------------- Dataset Info ---------------------------------
[2018-09-07 20:41:42 @dataset.py:36] fn_preprocess: None
[2018-09-07 20:41:42 @dataset.py:36] queue_size: 256
[2018-09-07 20:41:42 @dataset.py:36] file_length: 32766
[2018-09-07 20:41:42 @dataset.py:36] return_fnames: False
[2018-09-07 20:41:42 @dataset.py:36] shapes: [[256, 256, 3]]
[2018-09-07 20:41:42 @dataset.py:36] random: False
[2018-09-07 20:41:42 @dataset.py:36] dtypes: [tf.float32]
[2018-09-07 20:41:42 @dataset.py:36] index: 0
[2018-09-07 20:41:42 @dataset.py:36] enqueue_size: 32
[2018-09-07 20:41:42 @dataset.py:36] random_crop: False
[2018-09-07 20:41:42 @dataset.py:36] nthreads: 8
[2018-09-07 20:41:42 @dataset.py:36] batch_phs: [<tf.Tensor 'Placeholder:0' shape=(?, 256, 256, 3) dtype=float32>]
[2018-09-07 20:41:42 @dataset.py:36] filetype: image
[2018-09-07 20:41:42 @dataset.py:37] --------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    images, masks, guides, config=config)
  File "/home/kjm/Desktop/inpainting/GatedConvolution/inpaint_model_gc.py", line 161, in build_graph_with_losses
    batch_incomplete, batch_mask, batch_mask, config, reuse=reuse, training=training, padding=config.PADDING)
  File "/home/kjm/Desktop/inpainting/GatedConvolution/inpaint_model_gc.py", line 114, in build_inpaint_net
    x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)
  File "/home/kjm/Desktop/inpainting/GatedConvolution/inpaint_ops.py", line 512, in contextual_attention
    offset = tf.argmax(yi, axis=3, output_type=tf.int32)
TypeError: argmax() got an unexpected keyword argument 'output_type'

This is 'validation_shuffled.flist' file:
/home/kjm/Desktop/inpainting/GatedConvolution/data/validation/validation/047710.png
/home/kjm/Desktop/inpainting/GatedConvolution/data/validation/validation/047871.png
/home/kjm/Desktop/inpainting/GatedConvolution/data/validation/validation/046974.png

Thank you for your help!

**Comment by JiahuiYu** [comment]
@JinMengKang Please check tensor flow version. It seems the API has been changed. So you will need to change input to argmax as well.

**Comment by JinMengKang** [comment]
Sorry to disturb you, I tried to change the version of Tensor Flow in the last two days, but some mistakes still exist.
And I use python3.5+tensorflow1.4.0+cuda8+cudnn6.2.
A   “-conv2d() dilated--------”  error still occurred.
Is it necessary to install the version of Tensor Flow 1.5+?
Thank you very much for your patient answer

**Comment by JinMengKang** [comment]
Error detail is:
TypeError: conv2d() got an unexpected keyword argument 'dilated'
Is it convenient to tell me your environment version?
Thanks a lot!

**Comment by JiahuiYu** [comment]
python3.6+tensorflow1.4.0+cuda9+cudnn7.

Your setting should be fine. Please check the tensor flow version and make sure the API has not changed since you got an unexpected keyword argument 'dilated'.
