### ISSUE TITLE
add our masks when training

### ISSUE THREAD

**Issue by KangSH9776** [JiahuiYu/generative_inpainting#136]
I want to add specific image values to the existing mask.
The code for the existing mask part has been modified as shown below.

>> code
    def npmask(bbox, height, width, delta_h, delta_w):
        mask = np.zeros((1, height, width, 1), np.float32)
        h = np.random.randint(delta_h//2+1)
        w = np.random.randint(delta_w//2+1)
        mask[:, bbox[0]+h:bbox[0]+bbox[2]-h,
             bbox[1]+w:bbox[1]+bbox[3]-w, :] = 1.
        return mask
    with tf.variable_scope(name), tf.device('/cpu:0'):
        img_shape = config.IMG_SHAPES
        height = img_shape[0]
        width = img_shape[1]
        mask = tf.py_func(
            npmask,
            [bbox, height, width,
             config.MAX_DELTA_HEIGHT, config.MAX_DELTA_WIDTH],
            tf.float32, stateful=False)
        mask.set_shape([1] + [height, width] + [1])
        image_reader = tf.WholeFileReader()
        train_mask_image = tf.image.decode_png('/home/user/Documents/SSS/generative_inpainting-master/mask_using_train_mask.png')
        train_mask_image = tf.cast(train_mask_image, dtype = tf.float32)
        mask = tf.add(mask, tf.reshape(train_mask_image, (1, 256, 256, 1)))
    return mask

When you run the training, an error occurs as follows:

>>error
Traceback (most recent call last):
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with '/home/user/Docum'
     [[Node: mask_c_1/DecodePng = DecodePng[channels=0, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](mask_c_1/DecodePng/contents)]]
     [[Node: mask_c_1/Add/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_223_mask_c_1/Add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    trainer.train()
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/train/trainer.py", line 133, in train
    cb.run(sess, step)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/callbacks/secondary_trainer.py", line 26, in run
    self.train()
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/train/trainer.py", line 141, in train
    feed_dict=self.context['feed_dict'])
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with '/home/user/Docum'
     [[Node: mask_c_1/DecodePng = DecodePng[channels=0, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](mask_c_1/DecodePng/contents)]]
     [[Node: mask_c_1/Add/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_223_mask_c_1/Add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
Caused by op 'mask_c_1/DecodePng', defined at:
  File "train.py", line 87, in <module>
    'model': model, 'data': data, 'config': config, 'loss_type': 'd'},
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/callbacks/secondary_trainer.py", line 22, in __init__
    Trainer.__init__(self, primary=False, **context)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/train/trainer.py", line 41, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/train/trainer.py", line 250, in train_ops_and_losses
    loss = self.context['graph_def'](**graph_def_kwargs)
  File "train.py", line 23, in multigpu_graph_def
    images, config, reuse=True)
  File "/home/user/Documents/SSS/generative_inpainting-master/inpaint_model.py", line 149, in build_graph_with_losses
    mask = bbox2mask(bbox, config, name='mask_c')
  File "/home/user/Documents/SSS/generative_inpainting-master/inpaint_ops.py", line 150, in bbox2mask
    train_mask_image = tf.image.decode_png('/home/user/Documents/SSS/generative_inpainting-master/mask_using_train_mask.png')
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 1067, in decode_png
    name=name)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()
InvalidArgumentError (see above for traceback): Expected image (JPEG, PNG, or GIF), got unknown format starting with '/home/user/Docum'
     [[Node: mask_c_1/DecodePng = DecodePng[channels=0, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](mask_c_1/DecodePng/contents)]]
     [[Node: mask_c_1/Add/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_223_mask_c_1/Add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Q. How do you modify the code to add the desired image values to the random mask?

I always appreciate your interesting research.

**Comment by JiahuiYu** [comment]
Take [this](https://blog.csdn.net/Gavinmiaoc/article/details/81250782) as a reference. You can translate to english of the website.
