### ISSUE TITLE
Questions about multi-gpu training

### ISSUE THREAD

**Issue by RyanHTR** [JiahuiYu/generative_inpainting#14]
It's a great work. Does this code support multi-gpu training? I've tried to alter NUM_GPUS and GPU_ID, but it seems like that the code just selects one gpu for training. Is there any clue about it? Thanks.

**Comment by JiahuiYu** [comment]
To enable multi-GPU training, you will need to change [this line](https://github.com/JiahuiYu/generative_inpainting/blob/7be0964cfc3c1b274839281f4b6c5db67af62bbf/train.py#L90) to [MultiGPUTrainer](https://github.com/JiahuiYu/neuralgym/tree/c66107654253415af7b140b4cc293d091469fe00/neuralgym/train).
Expect some adventures when using multi-GPU for this project. I am not sure about the behavior.

**Comment by zhiweige** [comment]
@RyanHTR Hello, RyanHTR, can you train the network successfully on multi-GPU?

**Comment by 1900zyh** [comment]
@JiahuiYu There is a bug for 'NoneType object is not callable' [https://github.com/JiahuiYu/neuralgym/blob/c66107654253415af7b140b4cc293d091469fe00/neuralgym/train/multigpu_trainer.py#L70](url)

**Comment by JiahuiYu** [comment]
@1900zyh This is not bug. Loss should be None for multi-GPU training.

**Comment by 1900zyh** [comment]
@JiahuiYu  I think it should be
 `assert loss is None, 'For multigpu training, graph_def should be provided, instead of loss.'`
Or it will report TypeError

**Comment by JiahuiYu** [comment]
@1900zyh Ohhhh I see. Thank you!

**Comment by DAA233** [comment]
@JiahuiYu I have followed the above instructions (change `Trainer` to `MultiGPUTrainer`, add `num_gpus` argument), however, I met the following problem:

```log
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    log_dir=log_prefix,
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/neuralgym/train/multigpu_trainer.py", line 28,
in __init__
    super().__init__(**self.context)
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/neuralgym/train/trainer.py", line 56, in __ini$__
    self.init_primary_trainer()
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/neuralgym/train/trainer.py", line 93, in init_$rimary_trainer
    self.context['log_dir'], self.context['sess'].graph)
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", l$
ne 337, in __init__
    super(FileWriter, self).__init__(event_writer, graph, graph_def)
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", l$
ne 80, in __init__
    self.add_graph(graph=graph, graph_def=graph_def)
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", l$
ne 190, in add_graph
    true_graph_def = graph.as_graph_def(add_shapes=True)
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2773$
 in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/home/ouc/.local/share/virtualenvs/mosaic-kYYZNXgR/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2733$
 in _as_graph_def
    raise ValueError("GraphDef cannot be larger than 2GB.")
ValueError: GraphDef cannot be larger than 2GB.
```

**Comment by bis-carbon** [comment]
I have 4 GTX 1080Ti GPUs and each gpu can handle batch size of 16 that means if I use all the gpus I can change batch size to 64. But when I do that my GPUs ran out of memory.
Am assuming here that ng.train.MultiGPUTrainer uses data parallelism to split input data (64 batch size) in to 4 gpus where each gpu gets 16 batch of images.

Because of that Issue I can only train on batch size of 16, whether I use 4 gpus or 1 gpu.
What are your thoughts about this?

**Comment by JiahuiYu** [comment]
@bis-carbon  The batch size here is the per-gpu batch size.

**Comment by bis-carbon** [comment]
Thank you for your quick response and great work.

**Comment by Adhiyaman-Manickam** [comment]
@bis-carbon hi. have you figured out the issues that how to use multi gpu, if so kindly let me know. Thanks in advance

**Comment by Adhiyaman-Manickam** [comment]
@1900zyh @bis-carbon @lipanpeng Hi. Have you figured out the issues that how to use multi gpu for training. If so, kinldy let me know, I am struggling. Thanks in advance
