### ISSUE TITLE
Error by finding the gpu index.

### ISSUE THREAD

**Issue by patriciaVitoria** [JiahuiYu/generative_inpainting#142]
I have a gpu (GK104 [GeForce GTX 760]) and I would like to test your code. I used pretrained data...but i get the following error.
Any help? 
Thanks in advance.

python test.py --image examples/input.png --mask examples/center_mask
_256.png --output examples/output.png --checkpoint model_logs/release_celeba_hq_256/
[2018-09-21 15:45:25 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[2018-09-21 15:45:25 @__init__.py:80] Saving logging to file: neuralgym_logs/20180921154525035034.
Not supported on the device(s)
Failed to process command line 

Traceback (most recent call last):
  File "test.py", line 23, in <module>
    ng.get_gpus(1)
  File "/home/u64353/venvpytorch/lib/python3.6/site-packages/neuralgym/utils/gpus.py", line 54, in get_gpus
    gpu_id = int(s[0])
IndexError: list index out of range

**Comment by JiahuiYu** [comment]
@patriciaVitoria Hi, please have a look of the issue #47.
