### ISSUE TITLE
I want to add our masks.

### ISSUE THREAD

**Issue by KangSH9776** [JiahuiYu/generative_inpainting#153]
In the 'bbox2mask' function to create a random mask, I modified the code part corresponding to the random mask in order to add the desired our mask value to the mask value by like below.

We added our_mask in 'npmask' function to set the white area of ​​our_mask to '1.', the black area to '0', and the initial value of mask to our_mask.

>>code
def bbox2mask(bbox, config, name='mask'):
    """Generate mask tensor from bbox.

    Args:
        bbox: configuration tuple, (top, left, height, width)
        config: Config should have configuration including IMG_SHAPES,
            MAX_DELTA_HEIGHT, MAX_DELTA_WIDTH.

    Returns:
        tf.Tensor: output with shape [1, H, W, 1]

    """
    def npmask(bbox, height, width, delta_h, delta_w):
        our_mask = cv2.imread('addmask.png', cv2.IMREAD_GRAYSCALE)
        our_mask = np.place(our_mask, our_mask == 254, 1.)

        mask = np.zeros((1, height, width, 1), np.float32)
        mask[0,:, :, 0] = our_mask
        h = np.random.randint(delta_h//2+1)
        w = np.random.randint(delta_w//2+1)
        mask[:, bbox[0]+h:bbox[0]+bbox[2]-h,
             bbox[1]+w:bbox[1]+bbox[3]-w, :] = 1.
        return mask
    with tf.variable_scope(name), tf.device('/cpu:0'):
        img_shape = config.IMG_SHAPES
        height = img_shape[0]
        width = img_shape[1]
        mask = tf.py_func(
            npmask,
            [bbox, height, width,
             config.MAX_DELTA_HEIGHT, config.MAX_DELTA_WIDTH],
            tf.float32, stateful=False)
        mask.set_shape([1] + [height, width] + [1])
    return mask

However, the following error code has occurred.
>>error

Traceback (most recent call last):
  File "train.py", line 112, in <module>
    trainer.train()
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/train/trainer.py", line 133, in train
    cb.run(sess, step)
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/callbacks/secondary_trainer.py", line 26, in run
    self.train()
  File "/home/user/Documents/SSS/generate3/lib/python3.5/site-packages/neuralgym/train/trainer.py", line 143, in train
    assert not np.isnan(loss_value)
AssertionError

Can i ask your advice about the cause of the error and the problem of the code modification?

**Comment by KangSH9776** [comment]
Refer to issue #39 and correct the code again.
Invalid use of np.place function.
Thank you for reading it.

**Comment by KangSH9776** [comment]
Refer to issue #39 and correct the code again.
Invalid use of np.place function.
Thank you for reading it.
