### ISSUE TITLE
Sry to bother u again

### ISSUE THREAD

**Issue by xiayq1** [JiahuiYu/generative_inpainting#159]
# training data
    #"""
    #with open(config.DATA_FLIST[config.DATASET][0]) as f:
        #fnames = f.read().splitlines()
    fnames=['img010.png','img000.png']

I  change the code in train.py.
Then it can run now.
In the end it will give me information like this:
2018-10-15 15:52:31 @weights_viewer.py:60] Total size of trainable weights: 0G 10M 108K 392B (Assuming32-bit data type.)
But it also produced the model.
Then I run the test.

tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file model_logs\20181015153040966844_imagenet_NORMAL_wgan_gp_LOG_DIR\events.out.tfevents.1539588647.NBA1903: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

Is this means my training fails?
Should I increase my training dataset or doing something else to solve the problem?
I am still trying it on Win10.

**Comment by aiueogawa** [comment]
@xiayq1 
> tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file model_logs\20181015153040966844_imagenet_NORMAL_wgan_gp_LOG_DIR\events.out.tfevents.1539588647.NBA1903: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

told you the model file (model_logs\20181015153040966844_imagenet_NORMAL_wgan_gp_LOG_DIR\events.out.tfevents.1539588647.NBA1903) you specified is wrong. This file with events.out.tfevents as its extension is  a summary file used for TensorBoard.
Specify the correct file as model.

**Comment by aiueogawa** [comment]
@xiayq1
I haven't run this project yet but I've read this codes to some extent for understanding. And I work on not Win10 but macOS.

If this error is because opencv cannot read images, you should comfirm that image paths are right.

However, I suspect that this error does not stem from opencv read error because neuralgym seems to check read error.
Hence, you should check where is the first place where None came from with debugger or print function.

**Comment by xiayq1** [comment]
>           @xiayq1
> I haven't run this project yet but I've read this codes to some extent for understanding. And I work on not Win10 but macOS.
> If this error is because opencv cannot read images, you should comfirm that image paths are right. In my experience, opencv read error almost always comes from wrong path.
> However, I suspect that this error does not stem from opencv read error because neuralgym seems to check read error.
> Hence, you should check where is the first place where None came from with debugger or print function.

Thx

**Comment by aiueogawa** [comment]
@xiayq1 I'm sorry but I don't understand  to begin with, why you need to fix as follows:

```
# training data
#"""
#with open(config.DATA_FLIST[config.DATASET][0]) as f:
    #fnames = f.read().splitlines()
fnames=['buffer010.png','buffer000.png']
```

You said 

>I change the code here (fnames). Because there are something wrong with the Unicode.

What fact make you think so?

**Comment by xiayq1** [comment]
> @xiayq1 I'm sorry but I don't understand to begin with, why you need to fix as follows:
> 
> ```
> # training data
> #"""
> #with open(config.DATA_FLIST[config.DATASET][0]) as f:
>     #fnames = f.read().splitlines()
> fnames=['buffer010.png','buffer000.png']
> ```
> You said
> 
> > I change the code here (fnames). Because there are something wrong with the Unicode.
> 
> What fact make you think so?

 It will show 'charmap' codec can't decode byte 0x81 in position 967: character maps to <undefined>

**Comment by xiayq1** [comment]
> @xiayq1 I'm sorry but I don't understand to begin with, why you need to fix as follows:
> 
> ```
> # training data
> #"""
> #with open(config.DATA_FLIST[config.DATASET][0]) as f:
>     #fnames = f.read().splitlines()
> fnames=['buffer010.png','buffer000.png']
> ```
> You said
> 
> > I change the code here (fnames). Because there are something wrong with the Unicode.
> 
> What fact make you think so?

I asked the question in #157

**Comment by aiueogawa** [comment]
@xiayq1 OK. Please show full error message about codec.

**Comment by xiayq1** [comment]
> @xiayq1 OK. Please show full error message about codec.

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 967: character maps to <undefined> I believe this is the full msg. If will check it tomorrow. Thx a lot

**Comment by aiueogawa** [comment]
@xiayq1 This is not enough. Show me full message including stack trace tomorrow.

**Comment by xiayq1** [comment]
> @xiayq1 This is not enough. Show me full message including stack trace tomorrow.

I will. Thx.

**Comment by JiahuiYu** [comment]
@aiueogawa Thanks for your help!

**Comment by xiayq1** [comment]
>           @xiayq1 This is not enough. Show me full message including stack trace tomorrow.

Traceback (most recent call last):
  File "D:/inpainting/py/generative_inpainting-master/generative_inpainting-master/train.py", line 41, in <module>
    fnames = f.read().splitlines()
  File "C:\Users\peeyqxia\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 967: character maps to <undefined>

Here is the full msg.

**Comment by xiayq1** [comment]
imagenet: [
    'data\imagenet\buffer010.png',
  ]
this is my .yml file. I only want to train on one image.

**Comment by xiayq1** [comment]
>           @xiayq1 You cannot do like this. Please add 'data\imagenet\buffer010.png' to a file and then use
> imagenet: [
> your_file.flist,
> ]

What means "your_file.flist"? How can I create a file.flist? How can I add 'data\imagenet\buffer010.png' to a file? Can u show me? Thx a lot.

**Comment by JiahuiYu** [comment]
@xiayq1 Please input data\imagenet\buffer010.png to the file named file.flist. Then let's say your file name is file.flist, you will need to modify:

imagenet: [
your_file.flist,
]

I do think you will need to ask someone else to help you on basic programming knowledges. And please do not open new issues since they are redundant.

**Comment by JiahuiYu** [comment]
You can just use openCV to open the file to check if it is working or not. I have no experience on Windows. Try

f = cv2.open(fnames[0])

**Comment by JiahuiYu** [comment]
Image is None usually means the openCV cannot find the image file.

**Comment by xiayq1** [comment]
>           You can just use openCV to open the file to check if it is working or not. I have no experience on Windows. Try
> f = cv2.open(fnames[0])

Thx. I will try

**Comment by JiahuiYu** [comment]
Hope it works for you. Basically my code is trying to read files in fnames using openCV, and do shuffling and resizing etc. So if you can open the file list using openCV directly, it should also work with neuralgym.

**Comment by xiayq1** [comment]
I still have one question. Because my memory is limited. If my training dataset shape is [104,104,3], can I use a image [2048 ,2048, 3] as my test. The training dataset[104,104,3] is the crop image of test image[2048,2048,3].

**Comment by JiahuiYu** [comment]
We use 256x256 for training and 512x680 for testing. In your case you probably can have a try.

**Comment by xiayq1** [comment]
>           We use 256x256 for training and 512x680 for testing. In your case you probably can have a try.

Thx, I also wanna ask what means TRAIN_SPE, VAL_PSTEPS, MAX_DELTA_HEIGHT,MAX_DELTA_WIDTH. Do u have a document to introduce these parameter? Thx a lot.

**Comment by JiahuiYu** [comment]
You will find the meaning when you run the code. By the way I do encourage you to read the code, these parameters are already documented if you look deeper into documentation of this code and neuralgym library.

**Comment by xiayq1** [comment]
>           You will find the meaning when you run the code. By the way I do encourage you to read the code, these parameters are already documented if you look deeper into documentation of this code and neuralgym library.

Thx. Because I just want use it. But I will follow ur suggestion and try to understand it.

**Comment by xiayq1** [comment]
[32m[2018-10-18 15:31:28 @__init__.py:80][0m Saving logging to file: neuralgym_logs/20181018153128465879.
'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
[32m[2018-10-18 15:31:31 @gpus.py:39][0m Error reading GPU information, set no GPU.
Shape of image: (104, 104, 3)
Model loaded.

Is this the correct information if I use run test.py? Because the output image didn't seems changed.

**Comment by xiayq1** [comment]
I only use 2 images as my training dataset. (My batch size is 2, iter=10,epoch=10). I set the crop as true. Then I crop the train image, as my test image, but the output image is the same test image. Should I increase my dataset or increase my epoch? Do u have any suggestions?

**Comment by JiahuiYu** [comment]
We do not currently support Windows. Please use Linux instead.

**Comment by xiayq1** [comment]
>           We do not currently support Windows. Please use Linux instead.

I am rally sry to bother u. But I truly believe it can be done on windows. I think it will be more convenient if people can use it on Win. I think the problem maybe on resume training. 
I modified MODEL_RESTORE flag in inpaint.yml. Then I run python train.py. It just produce the model I have written in inpaint.yml (in the model logs ).

**Comment by xiayq1** [comment]
I want to ask a question, if there is a fish in the water. I crop the fish. I just want to use the network to inpainting the crop-fish image. But I don't want to the fish come back to the image. I just want to the my image is full of water. How can I train these network?

**Comment by xiayq1** [comment]
What I want ask is it this network can do an arbitrary object removal?

**Comment by JiahuiYu** [comment]
I think you can random crop to achieve Inpainting water instead of fish. Because when you random crop, it is likely that you have cropped the background water. By the way, two training images are not enough. You should at least have 2000. For arbitrary mask, please checkout our second version DeepFill v2.

**Comment by JiahuiYu** [comment]
Your understanding is correct.

**Comment by xiayq1** [comment]
> Your understanding is correct.

Thx. It's so wired. I can't understand why it doesn't work out.

**Comment by JiahuiYu** [comment]
@xiayq1 Make sure the value is 1 for mask, 0 for background. Make sure it is 1, not 255 or others.

**Comment by xiayq1** [comment]
>           @xiayq1 Make sure the value is 1 for mask, 0 for background. Make sure it is 1, not 255 or others.

I use (1,1,1) for mask, (0,0,0) for background.

**Comment by xiayq1** [comment]
![without2_img -](https://user-images.githubusercontent.com/26889002/47349400-22d4e580-d6e6-11e8-8c80-0fba50543f54.png)

Is the inpainiting area is too large?

**Comment by xiayq1** [comment]
![without2_img -](https://user-images.githubusercontent.com/26889002/47349501-5b74bf00-d6e6-11e8-9e8c-ff71b9b2aa60.png)

Is this black area too large?

**Comment by xiayq1** [comment]
I change the mask to only have 1 channel. The value is (1) for mask, ( 0) for background. Still not work out.

**Comment by JiahuiYu** [comment]
@xiayq1 Since most of others can train/test successfully, the code should have no issue. Given the information you leave, I am not able to help further.

**Comment by xiayq1** [comment]
>           @xiayq1 Since most of others can train/test successfully, the code should have no issue. Given the information you leave, I am not able to help further.

![image](https://user-images.githubusercontent.com/26889002/47549966-412e2180-d930-11e8-9a92-673ff27ce630.png)
I believe the code have no issue. So I am asking do u think the black area is too large? Because I see most of the images are only crop by their center. I am sry for bother u for such a long time.

**Comment by JiahuiYu** [comment]
@xiayq1 It should be fine. In my experiences, as long as you train with these masks, you should have a relative good performance during testing as well.
