### ISSUE TITLE
KILLED PROCESS IN BETWEEN

### ISSUE THREAD

**Issue by xyzdcgan** [JiahuiYu/generative_inpainting#169]
MY process is killed automatically when i run train.py. I have created .flist file from the code which you wrote. please help me
![error](https://user-images.githubusercontent.com/44637302/47779991-78317800-dd20-11e8-98c9-b044586ca9c9.png)

**Comment by JiahuiYu** [comment]
Have you viewed all the logs (the prints before this screenshot), do you see any error?

**Comment by JiahuiYu** [comment]
@xyzdcgan Please also have a reference at issue #60

**Comment by xyzdcgan** [comment]
no there is no error, i checked each line of the output.

**Comment by JiahuiYu** [comment]
ng.get_gpus() will automatically select a GPU. Please contact using github issue here.

**Comment by JiahuiYu** [comment]
Do you have other Linux machines/servers to try? Maybe the memory limit etc (ulimit -a) force the program to be killed. I have never encountered this problem before.

**Comment by wangping1408** [comment]
@JiahuiYu hi jiahui I can only train when I store fewer images in the training set. Once the number of images is a little more, it will appear
[2018-12-28 16:58:51 @data_from_fnames.py:153] image is None, sleep this thread for 0.1s.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/wp/anaconda3/envs/tensorflow-gpu-wp/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/wp/anaconda3/envs/tensorflow-gpu-wp/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wp/anaconda3/envs/tensorflow-gpu-wp/lib/python3.5/site-packages/neuralgym/data/feeding_queue_runner.py", line 194, in _run
    data = func()
  File "/home/wp/anaconda3/envs/tensorflow-gpu-wp/lib/python3.5/site-packages/neuralgym/data/data_from_fnames.py", line 143, in <lambda>
    feed_dict_op=[lambda: self.next_batch()],
  File "/home/wp/anaconda3/envs/tensorflow-gpu-wp/lib/python3.5/site-packages/neuralgym/data/data_from_fnames.py", line 180, in next_batch
    random_h, random_w, align=False)  # use last rand
  File "/home/wp/anaconda3/envs/tensorflow-gpu-wp/lib/python3.5/site-packages/neuralgym/ops/image_ops.py", line 50, in np_random_crop
    image = np_scale_to_shape(image, shape, align=align)
  File "/home/wp/anaconda3/envs/tensorflow-gpu-wp/lib/python3.5/site-packages/neuralgym/ops/image_ops.py", line 23, in np_scale_to_shape
    imgh, imgw = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

[2018-12-28 16:58:51 @data_from_fnames.py:153] image is None, sleep this thread for 0.1s.
But I'am sure the image  exists and the path is correct. I hope you can give me some advices and i want to know the meaning of batches/sec parameter,Is it related to my gpu?

**Comment by JiahuiYu** [comment]
It is not related to number of images, gpus or others. I guess your file list is wrong, which means some paths of files are incorrect thus openCV finds the loaded image are None.

**Comment by srushti93** [comment]
I am having similar issue too! 
/Users/jt6w/Desktop/Screen Shot 2019-02-22 at 2.43.20 PM.png
