### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#217]
when I do python train.py, error occur:
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    import neuralgym as ng
  File "/home/zhangyongle/.conda/envs/Inpainting/lib/python3.6/site-packages/neuralgym/__init__.py", line 75, in <module>
    from .utils.config import Config
  File "/home/zhangyongle/.conda/envs/Inpainting/lib/python3.6/site-packages/neuralgym/utils/config.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
WHY?

**Comment by zhangyonle** [comment]
I got it, by ANACONDA install pyyaml
