### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by wenshitao** [JiahuiYu/generative_inpainting#263]
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    ng.get_gpus(1)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\neuralgym\utils\gpus.py", line 54, in get_gpus
    gpu_id = int(s[0])
IndexError: list index out of range

**Comment by JiahuiYu** [comment]
Hi,

Please search over closed issues and there should be answers.

**Comment by wenshitao** [comment]
Thank you very much
