### ISSUE TITLE
running program  error

### ISSUE THREAD

**Issue by lijhong** [JiahuiYu/generative_inpainting#29]
when I input my picture shape (63,44,3) and running train.py .  But It shows some errors like this:
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    images, config=config)
  File "/opencv/generative_inpainting/inpaint_model.py", line 153, in build_graph_with_losses
    padding=config.PADDING)
  File opencv/generative_inpainting/inpaint_model.py", line 97, in build_inpaint_net
    x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)
  File "/opencv/generative_inpainting/inpaint_ops.py", line 307, in contextual_attention
    yi = tf.nn.conv2d_transpose(yi, wi_center, tf.concat([[1], raw_fs[1:]], axis=0), strides=[1,rate,rate,1]) / 4.
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1187, in conv2d_transpose
    filter.get_shape()[3]))
ValueError: input channels does not match filter's input channels, 40 != 48
I don't know how to fix it. can you give me any suggestions? Thanks.

**Comment by JiahuiYu** [comment]
Please make sure the input is dividable by 8 with current implementation. You can simply use mirror padding on boundaries.

**Comment by lijhong** [comment]
It works.Thank you.
