### ISSUE TITLE
multigpu_graph_def() error

### ISSUE THREAD

**Issue by Lxiangyue** [JiahuiYu/generative_inpainting#308]
It's a great work! While I running 'train.py' in GPU, some error happens:

Traceback (most recent call last):
File "train.py", line 87, in <module>
     'model': model, 'data_flist': data, 'config': config, 'loss_type': 'd'},
File "/usr/local/lib/python3.5/dist-packages/neuralgym/callbacks/secondary_trainer.py", line 22, in __init__
     Trainer.__init__(self, primary=False, **context)
File "/usr/local/lib/python3.5/dist-packages/neuralgym/train/trainer.py", line 41, in __init__
     self._train_op, self._loss = self.train_ops_and_losses()
File "/usr/local/lib/python3.5/dist-packages/neuralgym/train/trainer.py", line 250, in train_ops_and_losses 
     loss = self.context['graph_def'](**graph_def_kwargs)
TypeError: multigpu_graph_def() got an unexpected keyword argument 'data_flist'

Why is this error raised?

**Comment by Lxiangyue** [comment]
I have dealt with this problem. The reason why this error occured is that the version of tensorflow-gpu is too high.

**Comment by JiahuiYu** [comment]
@Lxiangyue Thanks for your information.
