### ISSUE TITLE
AttributeError: 'list' object has no attribute 'set_shape'AttributeError: 'list' object has no attribute 'set_shape'

### ISSUE THREAD

**Issue by zhangbaijin** [JiahuiYu/generative_inpainting#315]

**Comment by zhangbaijin** [comment]
Traceback (most recent call last):
  File "/media/generative_inpainting-master/train.py", line 47, in <module>
    images, config=config)
  File "/media/generative_inpainting-master/inpaint_model.py", line 153, in build_graph_with_losses
    padding=config.PADDING)
  File "/media/generative_inpainting-master/inpaint_model.py", line 97, in build_inpaint_net
    x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)
  File "/media/generative_inpainting-master/inpaint_ops.py", line 314, in contextual_attention
    offsets.set_shape(int_bs[:3] + [2])
thanks  for your time!

**Comment by zhangbaijin** [comment]
the probelm occured when i run train.py

**Comment by JiahuiYu** [comment]
@zhangbaijin I guess you have modified the code. Please print the content of offsets. I guess it is a list in your modification, but a tensor in our original code.
