### ISSUE TITLE
Problem about test

### ISSUE THREAD

**Issue by ClayZhang0403** [JiahuiYu/generative_inpainting#321]
Hi @JiahuiYu ， i have some trobule when i run the test.py , i dont know what happen? 
Traceback (most recent call last):
  File "/home/clay/DL/generative_inpainting/test.py", line 56, in <module>
    var_value = tf.contrib.framework.load_variable(args.checkpoint_dir, from_name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/framework/python/framework/checkpoint_utils.py", line 80, in load_variable
    return reader.get_tensor(name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 334, in get_tensor
    status)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key inpaint_net/conv2_downsam-ple/kernel not found in checkpoint

thx for your reply

**Comment by JiahuiYu** [comment]
Maybe rename checkpoint.txt to checkpoint.
