### ISSUE TITLE
neuralgym get_gpus error

### ISSUE THREAD

**Issue by doublejtoh** [JiahuiYu/generative_inpainting#35]
gpu        pid  type    sm   mem   enc   dec   command
 Idx             C/G     %     %     %     %   name
    0      14891     C    90    67     0     0   python3        

Traceback (most recent call last):
  File "train.py", line 37, in <module>
    ng.get_gpus(config.NUM_GPUS)
  File "/home/gpuguest/Downloads/generative_inpainting/neuralgym/utils/gpus.py", line 70, in get_gpus
    ' [(gpu id: num of processes)]: {}'.format(sorted_gpus))
SystemError: No enough gpus for dedicated usage. [(gpu id: num of processes)]: [(0, 1)]

iwhy is this error raised..?

**Comment by limchaos** [comment]
Hi ,I raised the same problem  and  can you tell me why this happend,Thank you )
