### ISSUE TITLE
inpaint.yml "guieded False --> True" issue

### ISSUE THREAD

**Issue by leechae0** [JiahuiYu/generative_inpainting#369]
hi @JiahuiYu 
thanks for sharing your code. 
when i run the train.py it has a error log like this.
****
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
image is None, sleep this thread for 0.1s.
ERROR:tensorflow:Exception in QueueRunner: 'NoneType' object has no attribute 'shape'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/neuralgym/data/feeding_queue_runner.py", line 194, in _run
    data = func()
  File "/usr/local/lib/python3.6/dist-packages/neuralgym/data/data_from_fnames.py", line 142, in <lambda>
    feed_dict_op=[lambda: self.next_batch()],
  File "/usr/local/lib/python3.6/dist-packages/neuralgym/data/data_from_fnames.py", line 179, in next_batch
    random_h, random_w, align=False)  # use last rand
  File "/usr/local/lib/python3.6/dist-packages/neuralgym/ops/image_ops.py", line 50, in np_random_crop
    image = np_scale_to_shape(image, shape, align=align)
  File "/usr/local/lib/python3.6/dist-packages/neuralgym/ops/image_ops.py", line 23, in np_scale_to_shape
    imgh, imgw = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
****
i'm change some flag in inpaint.yml file (* guieded False --> True)
An error occurs only when the flag is changed to True(Guieded)
When it was flag 'False', it confirmed that it is good working

**Comment by JiahuiYu** [comment]
@leechae0 For guided version of our inpainting system, you will also need to modify:

1. Prepare a list of images with guided information (e.g., extract edges from your original list)
2. Change filelist file (e.g., as `image.jpg, guided_image.jpg`)

**Comment by leechae0** [comment]
thanks @JiahuiYu 

but how can i get the guided_image? using HED edge detector ?
and only training for guided_image? without origin image?

**Comment by JiahuiYu** [comment]
@leechae0 Yes. We use HED edge detector on the images. The model will be trained with (1) original image with masks, and (2) guided information (e.g., edge) with **reversed** mask (guided info only in masked region).
