### ISSUE TITLE
Exceptions when trying database with color channel 1

### ISSUE THREAD

**Issue by pancookie** [JiahuiYu/generative_inpainting#438]
Hello Jiahui, 

First of all, thanks so much for your amazing work and courtesy of sharing the code. 
However, I would appreciate it a lot if you could help check the error I got when training the model with my own database. 

I am handling the single channeled images, in the dimensions of [64, 64, 1] (H, W, Ch). I made modifications to the inpaint_model.py 

`x = gen_conv(x, FLAGS.img_shapes[2], 3, 1, activation=None, name='conv17')` (Line 66) 
and 
`x = gen_conv(x, FLAGS.img_shapes[2], 3, 1, activation=None, name='allconv17')` (Line 107)
also for the offset_flow, I simply slice a layer I feel like I have to keep the consistency of the dimensions between `x_stage1, x_stage2, offset_flow`.

But when I try to train the model each time it shows me the error:

```
ERROR:tensorflow:Exception in QueueRunner: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'
ERROR:tensorflow:Exception in QueueRunner: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yangpan/.local/lib/python3.7/site-packages/neuralgym/data/feeding_queue_runner.py", line 197, in _run
    sess.run(enqueue_op, feed_dict)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yangpan/.local/lib/python3.7/site-packages/neuralgym/data/feeding_queue_runner.py", line 197, in _run
    sess.run(enqueue_op, feed_dict)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'

ERROR:tensorflow:Exception in QueueRunner: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yangpan/.local/lib/python3.7/site-packages/neuralgym/data/feeding_queue_runner.py", line 197, in _run
    sess.run(enqueue_op, feed_dict)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'

ERROR:tensorflow:Exception in QueueRunner: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yangpan/.local/lib/python3.7/site-packages/neuralgym/data/feeding_queue_runner.py", line 197, in _run
    sess.run(enqueue_op, feed_dict)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yangpan/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 64, 64) for Tensor 'Placeholder:0', which has shape '(?, 64, 64, 1)'
```

I figured out the 32 is the `enqueue_size`. I doubt if it automatically squeezed the Tensor at the channel dimension. Could you please offer me some ideas to solve it?

My environment information:
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"

python 3.7.4
tensorflow 1.14.0

Bests,
Yang

**Comment by pancookie** [comment]
So I got some clues.

Somehow, in the stacking of the list of list in the function `next_batch()` of file `data_from_fnames.py` in the Neuralgym package. The batch_data of mine is of the shape **[32, 1, 64, 64]**, which ought to be in the shape **[32, 1, height, width, channel]**. And it runs perfectly when I fixed the issue by adding one more new axis!

**Comment by JiahuiYu** [comment]
Yes you are right.

**Comment by pancookie** [comment]
> Yes you are right.

Hi Jiahui, 
one quick question from my side and hope you could help clarify. 
When the color channel of the database is not in dimension 3, do we need to adjust the inpaint model?
Say, In the definition of `gen_conv()` the value of cnum decides whether to ignore the gated conv step.
And in the file `inpaint_model.py`, right before getting the two variables (x_stage1 and x_stage2), those two `gen_conv()` function takes 3 as the **cnum** parameter. Is 3 indicating the number of color channels or just designed like this? 


Thanks.

Regards,
Yang

**Comment by LP429** [comment]
Hi, @pancookie. I'm sorry to bother you. How do you change the 'offset_flow' to single channel? Could you give me some advice?Thank you very mach!!

**Comment by pancookie** [comment]
> ould you give me so

Hello @LP429 . 
I would not suggest changing it into single channel since the 'offset_flow' is handled in the three channeled RGB fashion. 
Instead, you could repeat the gay channel twice if your training data is of only one channel.
