### ISSUE TITLE
Train with multiple masks and images respectively

### ISSUE THREAD

**Issue by htn274** [JiahuiYu/generative_inpainting#444]
First of all, I am very grateful to your significant study. Now, I have customized your model to my problem. 
I have training data with predefined masks. So I customized your code to read it like:

```py
# Read flist input and mask image
with open(FLAGS.data_flist[FLAGS.dataset][0]) as f:
        fnames_input = f.read().splitlines()

with open(FLAGS.data_flist[FLAGS.dataset][1]) as f:
        fnames_mask = f.read().splitlines()
images, masks = data.data_pipeline(FLAGS.batch_size)
```
And I also adding **masks** parameter to **build_graph_with_losses**. 
Then I got stuck in **contextual_attention** with the error:

> Traceback (most recent call last):
  File "train.py", line 47, in <module>
    g_vars, d_vars, losses = model.build_graph_with_losses(FLAGS, images, masks)
  File "/media/duongbao/data/Dropbox/code/HydroViet/git/dem-fill/generative_inpainting/inpaint_model.py", line 159, in build_graph_with_losses
    padding=FLAGS.padding)
  File "/media/duongbao/data/Dropbox/code/HydroViet/git/dem-fill/generative_inpainting/inpaint_model.py", line 95, in build_inpaint_net
    x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)
  File "/media/duongbao/data/Dropbox/code/HydroViet/git/dem-fill/generative_inpainting/inpaint_ops.py", line 352, in contextual_attention
    yi = tf.nn.conv2d_transpose(yi, wi_center, tf.concat([[1], raw_fs[1:]], axis=0), strides=[1,rate,rate,1]) / 4.
  File "/home/duongbao/miniconda3/envs/nu/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1232, in conv2d_transpose
    filter.get_shape()[3]))
ValueError: input channels does not match filter's input channels, 16384 != 1024

I realized that images in a batch use a same mask. But I didn't know how to solve it.
Can you give me some ideas?
Thanks a lot.

**Comment by yongshuaihuang** [comment]
Hi, how did you solve the problem? I met the same question

**Comment by int2char** [comment]
change your batch size to 1 can solve the problem，the origin code set all  image in a batch with the same mask
