### ISSUE TITLE
Error in concat_10 - Dimension mismatch

### ISSUE THREAD

**Issue by syomantak** [JiahuiYu/generative_inpainting#453]
I am trying to train it on MNIST dataset (with RGB channel) and I am getting the following error (on master branch code):
```Traceback (most recent call last):
  File "train.py", line 91, in <module>
    log_dir=FLAGS.log_dir,
  File "/usr/local/lib/python3.6/dist-packages/neuralgym/train/multigpu_trainer.py", line 24, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "/usr/local/lib/python3.6/dist-packages/neuralgym/train/multigpu_trainer.py", line 75, in train_ops_and_losses
    gpu_id=gpu, **graph_def_kwargs)
  File "train.py", line 15, in multigpu_graph_def
    FLAGS, images, FLAGS, summary=True, reuse=True)
  File "/content/generative_inpainting/inpaint_model.py", line 181, in build_graph_with_losses
    tf.concat(viz_img, axis=2),
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/array_ops.py", line 1420, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/gen_array_ops.py", line 1257, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 28 and 24. Shapes are [16,28] and [16,24]. for 'concat_10' (op: 'ConcatV2') with input shapes: [16,28,28,3], [16,28,28,3], [16,28,28,3], [16,24,24,3], [] and with computed input tensors: input[4] = <2>.

```
How can I fix this? I made appropriate changes in the `yml` file but it seems the there is some other problem!

**Comment by syomantak** [comment]
I overcame the above problem by ignoring the offset matrix in inpaint_model.py but I ran into the following problem-
```
(4, 4, 96, 16)
(1, ?, ?, 9)
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    g_vars, d_vars, losses = model.build_graph_with_losses(FLAGS, images)
  File "/content/generative_inpainting/inpaint_model.py", line 159, in build_graph_with_losses
    padding=FLAGS.padding)
  File "/content/generative_inpainting/inpaint_model.py", line 95, in build_inpaint_net
    x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)
  File "/content/generative_inpainting/inpaint_ops.py", line 349, in contextual_attention
    yi = tf.nn.conv2d_transpose(yi, wi_center, tf.concat([[1], raw_fs[1:]], axis=0), strides=[1,rate,rate,1]) / 4.
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 1232, in conv2d_transpose
    filter.get_shape()[3]))
ValueError: input channels does not match filter's input channels, 9 != 16
```
The top 2 shapes are result of the following lines I inserted in inpaint_ops.py below '#3.1 paste center comment'
```
print(wi_center.shape)
print(yi.shape)
```
Any help would be great!

**Comment by JiahuiYu** [comment]
@CyanideBoy Cool, thanks for the information and feedback!
