### ISSUE TITLE
'Image is None' Problem

### ISSUE THREAD

**Issue by jiyoungAn** [JiahuiYu/generative_inpainting#48]
Hello, JiahuiYu.
Thank you for answering me.
However, I got this error again..
`
[2018-05-25 17:43:37 @data_from_fnames.py:153] image is None, sleep this thread for 0.1s.
Exception in thread Thread-16: Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/neuralgym/data/feeding_queue_runner.py", line 194, in _run
    data = func()
  File "/usr/local/lib/python3.5/dist-packages/neuralgym/data/data_from_fnames.py", line 143, in <lambda>
    feed_dict_op=[lambda: self.next_batch()],
  File "/usr/local/lib/python3.5/dist-packages/neuralgym/data/data_from_fnames.py", line 182, in next_batch
    img = cv2.resize(img, tuple(self.shapes[i][:-1]))
cv2.error: /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize`

It seems like there is no image.
I used code in #15 for creating flist.
They are all in "data_flist" file.
At inpaint.yml, I add DATA_FLIST: city: ['data_flist/city/train_shuffled.flist','data_flist/city/validation_shuffled.flist']
and Set dataset as city.

Below is log about my Dataset
`[2018-05-25 17:42:59 @dataset.py:26] --------------------------------- Dataset Info ---------------------------------
[2018-05-25 17:42:59 @dataset.py:36] fn_preprocess: None
[2018-05-25 17:42:59 @dataset.py:36] file_length: 726
[2018-05-25 17:42:59 @dataset.py:36] return_fnames: False
[2018-05-25 17:42:59 @dataset.py:36] nthreads: 16
[2018-05-25 17:42:59 @dataset.py:36] batch_phs: [<tf.Tensor 'Placeholder:0' shape=(?, 256, 256, 3) dtype=float32>]
[2018-05-25 17:42:59 @dataset.py:36] dtypes: [tf.float32]
[2018-05-25 17:42:59 @dataset.py:36] index: 0
[2018-05-25 17:42:59 @dataset.py:36] queue_size: 256
[2018-05-25 17:42:59 @dataset.py:36] filetype: image
[2018-05-25 17:42:59 @dataset.py:36] enqueue_size: 32
[2018-05-25 17:42:59 @dataset.py:36] random_crop: False
[2018-05-25 17:42:59 @dataset.py:36] random: False
[2018-05-25 17:42:59 @dataset.py:36] shapes: [[256, 256, 3]]
[2018-05-25 17:42:59 @dataset.py:37] --------------------------------------------------------------------------------`

What should I do?
Thank you.

**Comment by jiyoungAn** [comment]
It was my mistake.
sorry I solved it! thank you

**Comment by Lsiming** [comment]
Hi~ How did you solve this problem? I have the same problem

**Comment by Lsiming** [comment]
# @jiyoungAn Hi~ How did you solve this problem? I have the same problem

**Comment by JiahuiYu** [comment]
@Lsiming Please check carefully of your file list locations. Issue #15 is a reference.

**Comment by QishengLi** [comment]
New to DL here...

I am also having the same problem. The log information from ` Dataset Info` was all correct (having the correct length, etc.), and the paths in filelist is the absolute path and have been tested (e.g. `cv2.imread(path)` will work).

Where else could the problem be? Any help is appreciated!

**Comment by JiahuiYu** [comment]
@QishengLi Hi thanks for your interest first.

You can try to print inside the DataFromFNames function in our neuralgym code. I would still believe the problem is the path is incorrect. Double check the file paths especially if you are using Windows.
