### ISSUE TITLE
testing after guided training

### ISSUE THREAD

**Issue by wmpauli** [JiahuiYu/generative_inpainting#521]
After successfully training with guided switched on, I thought it would be time to test it. I used the script `test.py`, with some small modifications, to add the guide input as additional input.

```
    model = InpaintCAModel()
    image = cv2.imread(args.image)
    mask = cv2.imread(args.mask)
    sketch = cv2.imread(args.sketch)
    # mask = cv2.resize(mask, (0,0), fx=0.5, fy=0.5)

    assert image.shape == mask.shape

    h, w, _ = image.shape
    grid = 8
    image = image[:h//grid*grid, :w//grid*grid, :]
    mask = mask[:h//grid*grid, :w//grid*grid, :]
    sketch = sketch[:h//grid*grid, :w//grid*grid, :]
    print('Shape of image: {}'.format(image.shape))

    image = np.expand_dims(image, 0)
    mask = np.expand_dims(mask, 0)
    sketch = np.expand_dims(sketch, 0)
    input_image = np.concatenate([image, mask, sketch], axis=2)
```
I assume that this might not be the correct way of doing this, because I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 6 and 5. Shapes are [5,5,6,48] and [5,5,5,48]. for 'Assign' (op: 'Assign') with input shapes: [5,5,6,48], [5,5,5,48].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/azureuser/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/azureuser/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/project_billy/generative_inpainting/test.py", line 83, in <module>
    assign_ops.append(tf.assign(var, var_value))
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/home/azureuser/miniconda3/envs/inpainting/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 2 in both shapes must be equal, but are 6 and 5. Shapes are [5,5,6,48] and [5,5,5,48]. for 'Assign' (op: 'Assign') with input shapes: [5,5,6,48], [5,5,5,48].
```

**Comment by wmpauli** [comment]
I just discovered the file `guided_batch_test.py`, which is meant to be used for that purpose. Thanks
