### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor 

### ISSUE THREAD

**Issue by jcrbsa** [JiahuiYu/generative_inpainting#536]
The following error shows when I run the `python  train.py`
```
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/ops/layers.py:142: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/callbacks/npz_model_loader.py:31: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/ops/gan_ops.py:138: The name tf.layers.Conv2D is deprecated. Please use tf.compat.v1.layers.Conv2D instead.

---------------------------------- APP CONFIG ----------------------------------
num_gpus_per_job: 1
num_cpus_per_job: 4
num_hosts_per_job: 1
memory_per_job: 32
gpu_type: nvidia-tesla-p100
name: places2_gated_conv_v100
model_restore: 202211180000000001_bt4sa_model
dataset: bt4sa
random_crop: False
val: False
log_dir: logs/full_model_bt4sa_hq_256
gan: sngan
gan_loss_alpha: 1
gan_with_mask: True
discounted_mask: True
random_seed: False
padding: SAME
train_spe: 4000
max_iters: 100000000
viz_max_out: 10
val_psteps: 2000
data_flist: 
  celebahq: ['data/celeba_hq/train_shuffled.flist', 'data/celeba_hq/validation_static_view.flist']
  celeba: ['data/celeba/train_shuffled.flist', 'data/celeba/validation_static_view.flist']
  places2: ['data/places2/train_shuffled.flist', 'data/places2/validation_static_view.flist']
  imagenet: ['data/imagenet/train_shuffled.flist', 'data/imagenet/validation_static_view.flist']
  bt4sa: ['/content/generative_inpainting/train.py', '/content/generative_inpainting/val.py']
static_view_size: 30
img_shapes: [256, 256, 3]
height: 128
width: 128
max_delta_height: 32
max_delta_width: 32
batch_size: 16
vertical_margin: 0
horizontal_margin: 0
ae_loss: True
l1_loss: True
l1_loss_alpha: 1.0
guided: False
edge_threshold: 0.6
--------------------------------------------------------------------------------
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/data/data_from_fnames.py:85: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

--------------------------------- Dataset Info ---------------------------------
file_length: 102
random: False
random_crop: False
filetype: image
shapes: [[256, 256, 3]]
dtypes: [tf.float32]
return_fnames: False
batch_phs: [<tf.Tensor 'Placeholder:0' shape=(?, 256, 256, 3) dtype=float32>]
enqueue_size: 32
queue_size: 256
nthreads: 4
fn_preprocess: None
index: 0
--------------------------------------------------------------------------------
WARNING:tensorflow:From /content/generative_inpainting/inpaint_ops.py:117: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /content/generative_inpainting/inpaint_ops.py:143: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /content/generative_inpainting/inpaint_ops.py:151: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
WARNING:tensorflow:From /content/generative_inpainting/inpaint_ops.py:48: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/layers/convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /content/generative_inpainting/inpaint_ops.py:252: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

WARNING:tensorflow:From /content/generative_inpainting/inpaint_ops.py:284: calling extract_image_patches (from tensorflow.python.ops.array_ops) with ksizes is deprecated and will be removed in a future version.
Instructions for updating:
ksizes is deprecated, use sizes instead
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/ops/gan_ops.py:118: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/ops/summary_ops.py:72: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /content/generative_inpainting/inpaint_model.py:209: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /content/generative_inpainting/inpaint_model.py:210: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From train.py:62: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/math_grad.py:1375: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
------------------------- Context Of Secondary Trainer -------------------------
num_gpus: 1
optimizer: <tensorflow.python.training.adam.AdamOptimizer object at 0x7f35a08fb210>
var_list: [<tf.Variable 'discriminator/sn_patch_gan/conv1/kernel:0' shape=(5, 5, 4, 64) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv1/bias:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv2/kernel:0' shape=(5, 5, 64, 128) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv2/bias:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv3/kernel:0' shape=(5, 5, 128, 256) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv3/bias:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv4/kernel:0' shape=(5, 5, 256, 256) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv4/bias:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv5/kernel:0' shape=(5, 5, 256, 256) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv5/bias:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv6/kernel:0' shape=(5, 5, 256, 256) dtype=float32_ref>, <tf.Variable 'discriminator/sn_patch_gan/conv6/bias:0' shape=(256,) dtype=float32_ref>]
graph_def: <function multigpu_graph_def at 0x7f3619f96170>
graph_def_kwargs: {'model': <inpaint_model.InpaintCAModel object at 0x7f35a1904f90>, 'FLAGS': {}, 'data': <neuralgym.data.data_from_fnames.DataFromFNames object at 0x7f35a18edbd0>, 'loss_type': 'd'}
async_train: False
feed_dict: {}
max_iters: 1
log_dir: /tmp/neuralgym
spe: 1
grads_summary: False
log_progress: False
--------------------------------------------------------------------------------
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/ops/summary_ops.py:129: The name tf.summary.image is deprecated. Please use tf.compat.v1.summary.image instead.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/ops.py", line 2380, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'inpaint_net_3/ExtractImagePatches' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gradients_util.py", line 345, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/ops.py", line 2384, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'inpaint_net_3/ExtractImagePatches' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 91, in <module>
    log_dir=FLAGS.log_dir,
  File "/usr/local/lib/python3.7/dist-packages/neuralgym/train/multigpu_trainer.py", line 24, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "/usr/local/lib/python3.7/dist-packages/neuralgym/train/multigpu_trainer.py", line 78, in train_ops_and_losses
    grads = optimizer.compute_gradients(loss, var_list)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gradients_util.py", line 679, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gradients_util.py", line 350, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gradients_util.py", line 679, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/array_grad.py", line 933, in _ExtractImagePatchesGrad
    array_ops.ones([output_indices_num], dtype=grad.dtype),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2560, in ones
    output = _constant_if_small(one, shape, dtype, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2295, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 3052, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (gradients_5/inpaint_net_3/ExtractImagePatches_grad/mul_3:0) to a numpy array.
```

**Comment by jcrbsa** [comment]
Dowgrade tensorflow and numpy package, it worked o/
